-- MySQL Script generated by MySQL Workbench
-- 07/11/15 15:17:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bitchneldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bitchneldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bitchneldb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bitchneldb` ;

-- -----------------------------------------------------
-- Table `bitchneldb`.`restaurant_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitchneldb`.`restaurant_profile` (
  `restaurant_profile_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_name` VARCHAR(45) NOT NULL,
  `restaurant_email` VARCHAR(45) NULL,
  `restaurant_password` VARCHAR(45) NULL,
  `restaurant_description` MEDIUMTEXT NOT NULL,
  `restaurant_location` VARCHAR(45) NULL,
  `restaurant_img` BLOB NULL,
  `restaurant_creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`restaurant_profile_id`),
  UNIQUE INDEX `restaurant_id_UNIQUE` (`restaurant_profile_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitchneldb`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitchneldb`.`user_profile` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_email` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitchneldb`.`restaurant_gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitchneldb`.`restaurant_gallery` (
  `restaurant_gallery_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_profile_id` INT NOT NULL,
  `restaurant_picture` BLOB NULL,
  PRIMARY KEY (`restaurant_gallery_id`),
  INDEX `fk_restaurant_gallery_restaurant_profile1_idx` (`restaurant_profile_id` ASC),
  CONSTRAINT `fk_restaurant_gallery_restaurant_profile1`
    FOREIGN KEY (`restaurant_profile_id`)
    REFERENCES `bitchneldb`.`restaurant_profile` (`restaurant_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitchneldb`.`restaurant_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitchneldb`.`restaurant_menu` (
  `restaurant_menu_id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_profile_id` INT NOT NULL,
  `restaurant_menu_product` VARCHAR(45) NOT NULL,
  `menu_product_description` VARCHAR(45) NOT NULL,
  `menu_product_img` BLOB NULL,
  PRIMARY KEY (`restaurant_menu_id`),
  INDEX `fk_menu_product_restaurant_profile1_idx` (`restaurant_profile_id` ASC),
  CONSTRAINT `fk_menu_product_restaurant_profile1`
    FOREIGN KEY (`restaurant_profile_id`)
    REFERENCES `bitchneldb`.`restaurant_profile` (`restaurant_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bitchneldb`.`restaurant_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bitchneldb`.`restaurant_event` (
  `restaurant_event_id` INT NOT NULL,
  `restaurant_profile_id` INT NOT NULL,
  `event_name` VARCHAR(45) NULL,
  `event_description` MEDIUMTEXT NULL,
  `event_contact` VARCHAR(15) NULL,
  PRIMARY KEY (`restaurant_event_id`),
  INDEX `fk_restaurant_event_restaurant_profile1_idx` (`restaurant_profile_id` ASC),
  CONSTRAINT `fk_restaurant_event_restaurant_profile1`
    FOREIGN KEY (`restaurant_profile_id`)
    REFERENCES `bitchneldb`.`restaurant_profile` (`restaurant_profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
